### PR TITLE
Implement zstyle-based lookup

### PR DESCRIPTION
**Pull request by xPMo**
Benefits:

1. All in one function for better speed
2. Config can be the same as completion list-colors
2. Users who set list-colors styles globally will see them anywhere which reads them:

```zsh
# custom list-colors with extendedglob support
zstyle '*' list-colors "${(@s[:])LS_COLORS}" '(#i)license(|.*)=04'
zstyle '*' list-colors-extended true
# since completion system only uses '*' globs, give it the the LS_COLORS list
zstyle ':completion:*' list-colors "${(@s[:])LS_COLORS}" 
```

### CODE REVIEW

**Comment by xPMo** [comment]
I'm leaving the previous method in, but I will mark it as deprecated.

**Comment by xPMo** [comment]
Just got an idea for a way to speed it up and be more flexible: Define a list-style and use `zformat`. Configuration will look something like this from the user's end:

```
zstyle :completion:some-context list-format '%F%f%r%(h. -> %L%l%r.)'
```

**Comment by xPMo** [comment]
The new method also closes #1.

**Comment by xPMo** [comment]
I'm going to rewrite the README before tagging a new release.

**Comment by xPMo** [comment]
@Aloxaf I considered posting this over on fzf-tab, but I decided to just ping you here instead.

----

The next version of zsh-ls-colors (implemented now in master, but not considered stable until in a tagged release) will have a new API:

```zsh
ls-color::fmt -A -F '%F%f%r%(h.%I%i. ➤ %L%l%r)' :completion:whatever file1 file2 ...
print -rl $reply[file1] $reply[file2]
```

[asciicast](https://asciinema.org/a/hscCh2tIRye3h3lr52GehBDUh)

It supports filetype indicators like `ls -F` does, that's what the `%i` spec is.  I've seen that fzf-tab supports `@` and `/` indicators, this would add `=`, `*`, and `|` indicators.

As for speed, it's similar-to-faster than -ftb-colorize, mostly by virtue of being a single function:

```
# After having set -- .... x5000
# added an anon function to make the comparison more fair
( repeat 5000; do; () { ... }; done; ls-color::fmt -a :demo:other-context "$@)  0.48s user 0.11s system 99% cpu 0.588 total
( repeat 5000; do; -ftb-colorize $PWD; done; ) 0.55s user 0.14s system 99% cpu 0.693 total
```

However, it should be even faster in practice because it satisfies some other [[ checks ]] in `-ftb-generate-complist`, and the format passed to the function can be specified with null separators or other characters.

Also I see that Aloxaf/fzf-tab#32 is still open in part because of backreference-based coloring. I'm considering trying to implement that. In that case, the API would actually simplify, because it wouldn't make sense to separate the file/link/indicator colors and reset (currently %F, %L, %I and %r) from the filename, link name, or indicator (currently %f, %l, and %i), since the coloring would be mixed with the completion. It shouldn't be noticably slower in most cases since it most specs don't have a `(#b)` flag.

---

Tangent: Awesome wok on the module!

**Comment by Aloxaf** [comment]
Thanks for your amazing work! The new API seems neat and the speed is satistying.
----
In fact, the backreference-based coloring is conflict with fzf's group-based coloring so it is not necessary for fzf-tab. Please feel free to delay the implementation of this function.

**Comment by xPMo** [comment]
Alright, new version is tagged.

**Pull request merged**
